name: Conduit Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      Couchbase__ConnectionString: ${{ secrets.COUCHBASE__CONNECTIONSTRING }}
      Couchbase__Username: ${{ secrets.COUCHBASE__USERNAME }}
      Couchbase__Password: ${{ secrets.COUCHBASE__PASSWORD }}
      Couchbase__BucketName: ${{ secrets.COUCHBASE__BUCKETNAME }}
      Couchbase__ScopeName: ${{ secrets.COUCHBASE__SCOPENAME }}
      Couchbase__UsersCollectionName: ${{ secrets.COUCHBASE__USERSCOLLECTIONNAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore Conduit

    - name: Build
      run: dotnet build Conduit --no-restore

    - name: Run tests
      run: dotnet test Conduit --no-build --verbosity normal

    - name: Generate code coverage files
      run: dotnet test Conduit /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}